/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ist.meic.pa.FunctionalProfiler;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        WithFunctionalProfiler classUnderTest = new WithFunctionalProfiler();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
